// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Infrastructures.Data.Education;

#nullable disable

namespace PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Infrastructures.Data.Education.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EducationDb")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Core.Domain.Education.Entities.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("FoundedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FoundedAt");

                    b.Property<long?>("SchoolGroupId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("TaxIdentificationNumber");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("TradeName");

                    b.HasKey("Id");

                    b.HasIndex("SchoolGroupId");

                    b.ToTable("Schools", "EducationDb");
                });

            modelBuilder.Entity("PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Core.Domain.Education.Entities.SchoolGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("FoundedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FoundedAt");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("TaxIdentificationNumber");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("TradeName");

                    b.HasKey("Id");

                    b.ToTable("SchoolGroups", "EducationDb");
                });

            modelBuilder.Entity("PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Core.Domain.Education.Entities.School", b =>
                {
                    b.HasOne("PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Core.Domain.Education.Entities.SchoolGroup", "SchoolGroup")
                        .WithMany("Schools")
                        .HasForeignKey("SchoolGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SchoolGroup");
                });

            modelBuilder.Entity("PairCode.GestaoEscolar.Presentations.Web.MudBlazor.Core.Domain.Education.Entities.SchoolGroup", b =>
                {
                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
